# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "mhDQzVz5KEgNWw5cAiXW8cyMLkHX0i62LYtw+6IL3kWZJzHW+bJlfa2NwBTFonSBfJkPF66FO8yJQe2GC1RuhINkY5vd31Ua46IpIYQfBzf8PsJFooA5fi2FioNkrTmA93gO5aE+zY6mp9imiwf4vHEogMpAJMca/sR2MqgaJLvvfuqipbhT/O4KNeAjxAn1BqkFQgjd3eRX1FkmLLk+e2fz1C7h7QIAdve6mBAlv6kyNoGo6bEJkIowVxPEAKCd1+dil762gXZNFXyLjje03s6xW46UGFuGeioDfdZ79MsLJPC83FTV6+4Zuy1zUSgz0rmHKv7Z9LtBWkP5yWJFeBykIiOm6TBoKulgfWFyEb1vlhPsntAzlsQi10+Vi/ylV9N6Bfv4fr9Vz3SwiWezxJc2lzfUF+mQlV6EreZVSTG2MEKwU/NPRoqfiHc6UJT9D20AUQgA3sClnHeyGd9Qc/AbLyYNgIY6o93875NWE881qWr8eX4ILl0xpwtjyS11kvumHsrWT0mj1lz/w5FLZBTXQ6g8ktUkwf2CFAZ7Snii7aDgLjJaM80iyMWK3Hb4zarvvnNk06/F2DY4q+FAXlc33eDhWCpuvr9WPdQnOblYTMk3NHjUwxtNjDnqXjrwpIzRbPdoVhFavDWlyUpnuL2lMmiQQr0HURB6sQtEc1o="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
