appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: zgDYg9XAdbZElnGdDz61rI8BAZkfAmfPmtgHWRHyCpJ77juO4YG80+lQuB1JZf1L/EfNbaETW/OcATfxuYfgNP0cqTBFvMHLHoy+fA0xBawcpum/kyBlvsXHuePKlvj/0aZsnanWwJNsTMuP+9Yxs7Jjvrjnxf9RfmQ3UU11GFmvbrrabK3d7BVAbbYpMRogUX0VdvNuGeLgTWLYz6Dpl3soGreRdbeWiCVsSYRsUjGEAj6Up/6ImkNHlqImjp7zf8EV2rYLzaIqpUcH+VCMp/5M4v3XOhc7vSyfiyqWmKDPVxhm+h57rw6eO3XC04bnLXK8Jko7qyGhB6ukZNDH4jjV3ZEOEz/WcgWpPhHjrxHOtVNW38SynGcUgJGX+vss/7jjWh9qoZoEj8hgowlFp14xit2S422jdeMRzCGHNHL+FP0uhKWUg877jjttHBL8Ssp7ZawRhgv/mQVxETJ6Of30a2UpFsV/1FZ4qKP0Xmbn3gin4xsezsYK79hHIiG06j+EThL/d3p9zKFKK121pGONoTVsnxQOQ8Mdn4kqtvTwJFKbFUVRXoZuA692he+mchXSy6dFjOwhz6J0DbV1Or3/0fwImWKPcUZb8WGWn4BPashzsMw90yWD9jouwRNp/EtNucdrWjTo+Xi9hXowJwSNwUSFLl4tWYI9Y2ZaH20=}
