travis:
  secure:
    BINSTAR_TOKEN: mhDQzVz5KEgNWw5cAiXW8cyMLkHX0i62LYtw+6IL3kWZJzHW+bJlfa2NwBTFonSBfJkPF66FO8yJQe2GC1RuhINkY5vd31Ua46IpIYQfBzf8PsJFooA5fi2FioNkrTmA93gO5aE+zY6mp9imiwf4vHEogMpAJMca/sR2MqgaJLvvfuqipbhT/O4KNeAjxAn1BqkFQgjd3eRX1FkmLLk+e2fz1C7h7QIAdve6mBAlv6kyNoGo6bEJkIowVxPEAKCd1+dil762gXZNFXyLjje03s6xW46UGFuGeioDfdZ79MsLJPC83FTV6+4Zuy1zUSgz0rmHKv7Z9LtBWkP5yWJFeBykIiOm6TBoKulgfWFyEb1vlhPsntAzlsQi10+Vi/ylV9N6Bfv4fr9Vz3SwiWezxJc2lzfUF+mQlV6EreZVSTG2MEKwU/NPRoqfiHc6UJT9D20AUQgA3sClnHeyGd9Qc/AbLyYNgIY6o93875NWE881qWr8eX4ILl0xpwtjyS11kvumHsrWT0mj1lz/w5FLZBTXQ6g8ktUkwf2CFAZ7Snii7aDgLjJaM80iyMWK3Hb4zarvvnNk06/F2DY4q+FAXlc33eDhWCpuvr9WPdQnOblYTMk3NHjUwxtNjDnqXjrwpIzRbPdoVhFavDWlyUpnuL2lMmiQQr0HURB6sQtEc1o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
